version: "3.9"

services:
  pakasso-internetbanking:
    build: .
    ports:
      - "3000:3000"
    environment:
      BASE_URL: https://cba.pakassocredit.com
    extra_hosts:
      - "host.docker.internal:host-gateway"

